export interface Court {
  name: string;
  description: string;
  location: string;
  phones: string[];
  email: string;
  website: string;
  type: "Supreme Court" | "High Court" | "High Court Bench" | "District Court" | "Special Court";
  coordinates: [number, number]; // [lat, lng]
  parentCourt: string | null;
}

export const courtsData: Court[] = [
  {
    name: "Supreme Court of Nepal",
    description: "The Supreme Court of Nepal (सर्वोच्च अदालत) is the highest court in Nepal. It has appellate jurisdiction over decisions of the seven High Courts, extraordinary original jurisdiction, and serves as the guardian of the Constitution.",
    location: "Ramshah Path, Kathmandu 44600",
    phones: ["+977-1-4262546", "+977-1-4262895"],
    email: "info@supremecourt.gov.np",
    website: "http://www.supremecourt.gov.np",
    type: "Supreme Court",
    coordinates: [27.6936, 85.3228],
    parentCourt: null
  },
  {
    name: "Special Court of Nepal",
    description: "Established to handle cases related to corruption, money laundering, and specific government-interest cases.",
    location: "Babarmahal, Kathmandu",
    phones: ["+977-1-5326536"],
    email: "info@specialcourt.gov.np",
    website: "http://specialcourt.gov.np",
    type: "Special Court",
    coordinates: [27.6953, 85.3235],
    parentCourt: "Supreme Court of Nepal"
  },
  {
    name: "High Court Biratnagar",
    description: "The appellate jurisdiction court serving the provinces according to the federated structure of Nepal. Hears appeals from district courts.",
    location: "Biratnagar, Nepal",
    phones: ["+977-94-912755"],
    email: "info_biratnagar@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/biratnagar",
    type: "High Court",
    coordinates: [26.4575, 87.2768],
    parentCourt: "Supreme Court of Nepal"
  },
  {
    name: "High Court Janakpur",
    description: "The appellate jurisdiction court serving the provinces according to the federated structure of Nepal. Hears appeals from district courts.",
    location: "Janakpur, Nepal",
    phones: ["+977-10-756499"],
    email: "info_janakpur@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/janakpur",
    type: "High Court",
    coordinates: [26.7338, 85.931],
    parentCourt: "Supreme Court of Nepal"
  },
  {
    name: "High Court Patan",
    description: "The appellate jurisdiction court serving the provinces according to the federated structure of Nepal. Hears appeals from district courts.",
    location: "Patan, Nepal",
    phones: ["+977-63-351027"],
    email: "info_patan@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/patan",
    type: "High Court",
    coordinates: [27.6794, 85.3312],
    parentCourt: "Supreme Court of Nepal"
  },
  {
    name: "High Court Pokhara",
    description: "The appellate jurisdiction court serving the provinces according to the federated structure of Nepal. Hears appeals from district courts.",
    location: "Pokhara, Nepal",
    phones: ["+977-47-219585"],
    email: "info_pokhara@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/pokhara",
    type: "High Court",
    coordinates: [28.2146, 83.9906],
    parentCourt: "Supreme Court of Nepal"
  },
  {
    name: "High Court Surkhet",
    description: "The appellate jurisdiction court serving the provinces according to the federated structure of Nepal. Hears appeals from district courts.",
    location: "Surkhet, Nepal",
    phones: ["+977-74-515931"],
    email: "info_surkhet@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/surkhet",
    type: "High Court",
    coordinates: [28.6041, 81.6425],
    parentCourt: "Supreme Court of Nepal"
  },
  {
    name: "High Court Tulsipur",
    description: "The appellate jurisdiction court serving the provinces according to the federated structure of Nepal. Hears appeals from district courts.",
    location: "Tulsipur, Nepal",
    phones: ["+977-79-113703"],
    email: "info_tulsipur@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/tulsipur",
    type: "High Court",
    coordinates: [28.1378, 82.3015],
    parentCourt: "Supreme Court of Nepal"
  },
  {
    name: "High Court Dipayal",
    description: "The appellate jurisdiction court serving the provinces according to the federated structure of Nepal. Hears appeals from district courts.",
    location: "Dipayal, Nepal",
    phones: ["+977-16-241270"],
    email: "info_dipayal@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/dipayal",
    type: "High Court",
    coordinates: [29.2685, 80.9378],
    parentCourt: "Supreme Court of Nepal"
  },
  {
    name: "Achham District Court",
    description: "The court of first instance for Achham District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Achham District Headquarters, Nepal",
    phones: ["+977-18-924505"],
    email: "info_achham@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/achham",
    type: "District Court",
    coordinates: [29.11, 81.29],
    parentCourt: "High Court Dipayal"
  },
  {
    name: "Arghakhanchi District Court",
    description: "The court of first instance for Arghakhanchi District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Arghakhanchi District Headquarters, Nepal",
    phones: ["+977-99-452255"],
    email: "info_arghakhanchi@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/arghakhanchi",
    type: "District Court",
    coordinates: [27.9, 83.1],
    parentCourt: "High Court Tulsipur"
  },
  {
    name: "Baglung District Court",
    description: "The court of first instance for Baglung District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Baglung District Headquarters, Nepal",
    phones: ["+977-35-338587"],
    email: "info_baglung@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/baglung",
    type: "District Court",
    coordinates: [28.27, 83.59],
    parentCourt: "High Court Pokhara"
  },
  {
    name: "Baitadi District Court",
    description: "The court of first instance for Baitadi District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Baitadi District Headquarters, Nepal",
    phones: ["+977-48-320252"],
    email: "info_baitadi@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/baitadi",
    type: "District Court",
    coordinates: [29.56, 80.56],
    parentCourt: "High Court Dipayal"
  },
  {
    name: "Bajhang District Court",
    description: "The court of first instance for Bajhang District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Bajhang District Headquarters, Nepal",
    phones: ["+977-97-609706"],
    email: "info_bajhang@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/bajhang",
    type: "District Court",
    coordinates: [29.55, 81.2],
    parentCourt: "High Court Dipayal"
  },
  {
    name: "Bajura District Court",
    description: "The court of first instance for Bajura District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Bajura District Headquarters, Nepal",
    phones: ["+977-22-468812"],
    email: "info_bajura@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/bajura",
    type: "District Court",
    coordinates: [29.56, 81.56],
    parentCourt: "High Court Dipayal"
  },
  {
    name: "Banke District Court",
    description: "The court of first instance for Banke District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Banke District Headquarters, Nepal",
    phones: ["+977-37-522153"],
    email: "info_banke@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/banke",
    type: "District Court",
    coordinates: [28.05, 81.61],
    parentCourt: "High Court Tulsipur"
  },
  {
    name: "Bara District Court",
    description: "The court of first instance for Bara District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Bara District Headquarters, Nepal",
    phones: ["+977-78-924431"],
    email: "info_bara@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/bara",
    type: "District Court",
    coordinates: [27.15, 85.0],
    parentCourt: "High Court Janakpur"
  },
  {
    name: "Bardiya District Court",
    description: "The court of first instance for Bardiya District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Bardiya District Headquarters, Nepal",
    phones: ["+977-41-703659"],
    email: "info_bardiya@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/bardiya",
    type: "District Court",
    coordinates: [28.32, 81.36],
    parentCourt: "High Court Tulsipur"
  },
  {
    name: "Bhaktapur District Court",
    description: "The court of first instance for Bhaktapur District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Bhaktapur District Headquarters, Nepal",
    phones: ["+977-99-954176"],
    email: "info_bhaktapur@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/bhaktapur",
    type: "District Court",
    coordinates: [27.67, 85.42],
    parentCourt: "High Court Patan"
  },
  {
    name: "Bhojpur District Court",
    description: "The court of first instance for Bhojpur District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Bhojpur District Headquarters, Nepal",
    phones: ["+977-61-652437"],
    email: "info_bhojpur@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/bhojpur",
    type: "District Court",
    coordinates: [27.17, 87.05],
    parentCourt: "High Court Biratnagar"
  },
  {
    name: "Chitwan District Court",
    description: "The court of first instance for Chitwan District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Chitwan District Headquarters, Nepal",
    phones: ["+977-75-516945"],
    email: "info_chitwan@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/chitwan",
    type: "District Court",
    coordinates: [27.58, 84.43],
    parentCourt: "High Court Patan"
  },
  {
    name: "Dadeldhura District Court",
    description: "The court of first instance for Dadeldhura District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Dadeldhura District Headquarters, Nepal",
    phones: ["+977-98-987721"],
    email: "info_dadeldhura@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/dadeldhura",
    type: "District Court",
    coordinates: [29.3, 80.59],
    parentCourt: "High Court Dipayal"
  },
  {
    name: "Dailekh District Court",
    description: "The court of first instance for Dailekh District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Dailekh District Headquarters, Nepal",
    phones: ["+977-60-848280"],
    email: "info_dailekh@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/dailekh",
    type: "District Court",
    coordinates: [28.84, 81.71],
    parentCourt: "High Court Surkhet"
  },
  {
    name: "Dang District Court",
    description: "The court of first instance for Dang District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Dang District Headquarters, Nepal",
    phones: ["+977-45-804392"],
    email: "info_dang@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/dang",
    type: "District Court",
    coordinates: [28.11, 82.3],
    parentCourt: "High Court Tulsipur"
  },
  {
    name: "Darchula District Court",
    description: "The court of first instance for Darchula District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Darchula District Headquarters, Nepal",
    phones: ["+977-47-357080"],
    email: "info_darchula@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/darchula",
    type: "District Court",
    coordinates: [29.84, 80.6],
    parentCourt: "High Court Dipayal"
  },
  {
    name: "Dhading District Court",
    description: "The court of first instance for Dhading District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Dhading District Headquarters, Nepal",
    phones: ["+977-92-910264"],
    email: "info_dhading@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/dhading",
    type: "District Court",
    coordinates: [27.97, 84.89],
    parentCourt: "High Court Patan"
  },
  {
    name: "Dhankuta District Court",
    description: "The court of first instance for Dhankuta District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Dhankuta District Headquarters, Nepal",
    phones: ["+977-71-818551"],
    email: "info_dhankuta@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/dhankuta",
    type: "District Court",
    coordinates: [26.98, 87.34],
    parentCourt: "High Court Biratnagar"
  },
  {
    name: "Dhanusa District Court",
    description: "The court of first instance for Dhanusa District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Dhanusa District Headquarters, Nepal",
    phones: ["+977-27-918266"],
    email: "info_dhanusa@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/dhanusa",
    type: "District Court",
    coordinates: [26.73, 85.92],
    parentCourt: "High Court Janakpur"
  },
  {
    name: "Dolakha District Court",
    description: "The court of first instance for Dolakha District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Dolakha District Headquarters, Nepal",
    phones: ["+977-22-297242"],
    email: "info_dolakha@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/dolakha",
    type: "District Court",
    coordinates: [27.75, 86.13],
    parentCourt: "High Court Patan"
  },
  {
    name: "Dolpa District Court",
    description: "The court of first instance for Dolpa District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Dolpa District Headquarters, Nepal",
    phones: ["+977-29-836277"],
    email: "info_dolpa@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/dolpa",
    type: "District Court",
    coordinates: [29.13, 83.05],
    parentCourt: "High Court Surkhet"
  },
  {
    name: "Doti District Court",
    description: "The court of first instance for Doti District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Doti District Headquarters, Nepal",
    phones: ["+977-29-830028"],
    email: "info_doti@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/doti",
    type: "District Court",
    coordinates: [29.26, 80.93],
    parentCourt: "High Court Dipayal"
  },
  {
    name: "Eastern Rukum District Court",
    description: "The court of first instance for Eastern Rukum District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Eastern Rukum District Headquarters, Nepal",
    phones: ["+977-86-788231"],
    email: "info_easternrukum@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/easternrukum",
    type: "District Court",
    coordinates: [28.64, 82.8],
    parentCourt: "High Court Surkhet"
  },
  {
    name: "Gorkha District Court",
    description: "The court of first instance for Gorkha District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Gorkha District Headquarters, Nepal",
    phones: ["+977-53-543100"],
    email: "info_gorkha@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/gorkha",
    type: "District Court",
    coordinates: [28.24, 84.97],
    parentCourt: "High Court Pokhara"
  },
  {
    name: "Gulmi District Court",
    description: "The court of first instance for Gulmi District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Gulmi District Headquarters, Nepal",
    phones: ["+977-63-436707"],
    email: "info_gulmi@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/gulmi",
    type: "District Court",
    coordinates: [28.07, 83.25],
    parentCourt: "High Court Tulsipur"
  },
  {
    name: "Humla District Court",
    description: "The court of first instance for Humla District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Humla District Headquarters, Nepal",
    phones: ["+977-23-726034"],
    email: "info_humla@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/humla",
    type: "District Court",
    coordinates: [30.13, 81.82],
    parentCourt: "High Court Surkhet"
  },
  {
    name: "Ilam District Court",
    description: "The court of first instance for Ilam District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Ilam District Headquarters, Nepal",
    phones: ["+977-53-967112"],
    email: "info_ilam@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/ilam",
    type: "District Court",
    coordinates: [26.91, 87.93],
    parentCourt: "High Court Biratnagar"
  },
  {
    name: "Jajarkot District Court",
    description: "The court of first instance for Jajarkot District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Jajarkot District Headquarters, Nepal",
    phones: ["+977-51-856963"],
    email: "info_jajarkot@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/jajarkot",
    type: "District Court",
    coordinates: [28.85, 82.19],
    parentCourt: "High Court Surkhet"
  },
  {
    name: "Jhapa District Court",
    description: "The court of first instance for Jhapa District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Jhapa District Headquarters, Nepal",
    phones: ["+977-46-258403"],
    email: "info_jhapa@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/jhapa",
    type: "District Court",
    coordinates: [26.54, 88.08],
    parentCourt: "High Court Biratnagar"
  },
  {
    name: "Jumla District Court",
    description: "The court of first instance for Jumla District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Jumla District Headquarters, Nepal",
    phones: ["+977-64-395838"],
    email: "info_jumla@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/jumla",
    type: "District Court",
    coordinates: [29.27, 82.18],
    parentCourt: "High Court Surkhet"
  },
  {
    name: "Kailali District Court",
    description: "The court of first instance for Kailali District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Kailali District Headquarters, Nepal",
    phones: ["+977-28-919379"],
    email: "info_kailali@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/kailali",
    type: "District Court",
    coordinates: [28.66, 80.85],
    parentCourt: "High Court Dipayal"
  },
  {
    name: "Kalikot District Court",
    description: "The court of first instance for Kalikot District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Kalikot District Headquarters, Nepal",
    phones: ["+977-69-371851"],
    email: "info_kalikot@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/kalikot",
    type: "District Court",
    coordinates: [29.14, 81.62],
    parentCourt: "High Court Surkhet"
  },
  {
    name: "Kanchanpur District Court",
    description: "The court of first instance for Kanchanpur District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Kanchanpur District Headquarters, Nepal",
    phones: ["+977-42-603312"],
    email: "info_kanchanpur@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/kanchanpur",
    type: "District Court",
    coordinates: [28.85, 80.33],
    parentCourt: "High Court Dipayal"
  },
  {
    name: "Kapilvastu District Court",
    description: "The court of first instance for Kapilvastu District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Kapilvastu District Headquarters, Nepal",
    phones: ["+977-44-990839"],
    email: "info_kapilvastu@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/kapilvastu",
    type: "District Court",
    coordinates: [27.63, 83.05],
    parentCourt: "High Court Tulsipur"
  },
  {
    name: "Kaski District Court",
    description: "The court of first instance for Kaski District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Kaski District Headquarters, Nepal",
    phones: ["+977-59-762196"],
    email: "info_kaski@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/kaski",
    type: "District Court",
    coordinates: [28.26, 83.97],
    parentCourt: "High Court Pokhara"
  },
  {
    name: "Kathmandu District Court",
    description: "The court of first instance for Kathmandu District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Kathmandu District Headquarters, Nepal",
    phones: ["+977-83-375593"],
    email: "info_kathmandu@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/kathmandu",
    type: "District Court",
    coordinates: [27.71, 85.32],
    parentCourt: "High Court Patan"
  },
  {
    name: "Kavrepalanchok District Court",
    description: "The court of first instance for Kavrepalanchok District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Kavrepalanchok District Headquarters, Nepal",
    phones: ["+977-36-318986"],
    email: "info_kavrepalanchok@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/kavrepalanchok",
    type: "District Court",
    coordinates: [27.62, 85.55],
    parentCourt: "High Court Patan"
  },
  {
    name: "Khotang District Court",
    description: "The court of first instance for Khotang District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Khotang District Headquarters, Nepal",
    phones: ["+977-89-681836"],
    email: "info_khotang@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/khotang",
    type: "District Court",
    coordinates: [27.2, 86.8],
    parentCourt: "High Court Biratnagar"
  },
  {
    name: "Lalitpur District Court",
    description: "The court of first instance for Lalitpur District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Lalitpur District Headquarters, Nepal",
    phones: ["+977-99-416787"],
    email: "info_lalitpur@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/lalitpur",
    type: "District Court",
    coordinates: [27.66, 85.32],
    parentCourt: "High Court Patan"
  },
  {
    name: "Lamjung District Court",
    description: "The court of first instance for Lamjung District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Lamjung District Headquarters, Nepal",
    phones: ["+977-16-658230"],
    email: "info_lamjung@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/lamjung",
    type: "District Court",
    coordinates: [28.23, 84.4],
    parentCourt: "High Court Pokhara"
  },
  {
    name: "Mahottari District Court",
    description: "The court of first instance for Mahottari District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Mahottari District Headquarters, Nepal",
    phones: ["+977-23-658282"],
    email: "info_mahottari@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/mahottari",
    type: "District Court",
    coordinates: [26.85, 85.8],
    parentCourt: "High Court Janakpur"
  },
  {
    name: "Makwanpur District Court",
    description: "The court of first instance for Makwanpur District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Makwanpur District Headquarters, Nepal",
    phones: ["+977-14-678160"],
    email: "info_makwanpur@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/makwanpur",
    type: "District Court",
    coordinates: [27.42, 85.03],
    parentCourt: "High Court Patan"
  },
  {
    name: "Manang District Court",
    description: "The court of first instance for Manang District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Manang District Headquarters, Nepal",
    phones: ["+977-17-959132"],
    email: "info_manang@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/manang",
    type: "District Court",
    coordinates: [28.55, 84.02],
    parentCourt: "High Court Pokhara"
  },
  {
    name: "Morang District Court",
    description: "The court of first instance for Morang District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Morang District Headquarters, Nepal",
    phones: ["+977-22-825523"],
    email: "info_morang@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/morang",
    type: "District Court",
    coordinates: [26.66, 87.49],
    parentCourt: "High Court Biratnagar"
  },
  {
    name: "Mugu District Court",
    description: "The court of first instance for Mugu District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Mugu District Headquarters, Nepal",
    phones: ["+977-33-806613"],
    email: "info_mugu@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/mugu",
    type: "District Court",
    coordinates: [29.53, 82.16],
    parentCourt: "High Court Surkhet"
  },
  {
    name: "Mustang District Court",
    description: "The court of first instance for Mustang District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Mustang District Headquarters, Nepal",
    phones: ["+977-99-488004"],
    email: "info_mustang@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/mustang",
    type: "District Court",
    coordinates: [28.99, 83.99],
    parentCourt: "High Court Pokhara"
  },
  {
    name: "Myagdi District Court",
    description: "The court of first instance for Myagdi District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Myagdi District Headquarters, Nepal",
    phones: ["+977-99-316894"],
    email: "info_myagdi@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/myagdi",
    type: "District Court",
    coordinates: [28.54, 83.56],
    parentCourt: "High Court Pokhara"
  },
  {
    name: "Nawalpur District Court",
    description: "The court of first instance for Nawalpur District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Nawalpur District Headquarters, Nepal",
    phones: ["+977-39-719306"],
    email: "info_nawalpur@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/nawalpur",
    type: "District Court",
    coordinates: [27.69, 84.05],
    parentCourt: "High Court Pokhara"
  },
  {
    name: "Nuwakot District Court",
    description: "The court of first instance for Nuwakot District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Nuwakot District Headquarters, Nepal",
    phones: ["+977-78-388491"],
    email: "info_nuwakot@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/nuwakot",
    type: "District Court",
    coordinates: [27.9, 85.16],
    parentCourt: "High Court Patan"
  },
  {
    name: "Okhaldhunga District Court",
    description: "The court of first instance for Okhaldhunga District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Okhaldhunga District Headquarters, Nepal",
    phones: ["+977-71-998130"],
    email: "info_okhaldhunga@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/okhaldhunga",
    type: "District Court",
    coordinates: [27.31, 86.5],
    parentCourt: "High Court Biratnagar"
  },
  {
    name: "Palpa District Court",
    description: "The court of first instance for Palpa District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Palpa District Headquarters, Nepal",
    phones: ["+977-39-364277"],
    email: "info_palpa@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/palpa",
    type: "District Court",
    coordinates: [27.86, 83.55],
    parentCourt: "High Court Tulsipur"
  },
  {
    name: "Panchthar District Court",
    description: "The court of first instance for Panchthar District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Panchthar District Headquarters, Nepal",
    phones: ["+977-11-239871"],
    email: "info_panchthar@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/panchthar",
    type: "District Court",
    coordinates: [27.15, 87.75],
    parentCourt: "High Court Biratnagar"
  },
  {
    name: "Parasi District Court",
    description: "The court of first instance for Parasi District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Parasi District Headquarters, Nepal",
    phones: ["+977-52-460069"],
    email: "info_parasi@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/parasi",
    type: "District Court",
    coordinates: [27.53, 83.66],
    parentCourt: "High Court Tulsipur"
  },
  {
    name: "Parbat District Court",
    description: "The court of first instance for Parbat District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Parbat District Headquarters, Nepal",
    phones: ["+977-53-665066"],
    email: "info_parbat@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/parbat",
    type: "District Court",
    coordinates: [28.21, 83.67],
    parentCourt: "High Court Pokhara"
  },
  {
    name: "Parsa District Court",
    description: "The court of first instance for Parsa District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Parsa District Headquarters, Nepal",
    phones: ["+977-55-804255"],
    email: "info_parsa@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/parsa",
    type: "District Court",
    coordinates: [27.15, 84.85],
    parentCourt: "High Court Janakpur"
  },
  {
    name: "Pyuthan District Court",
    description: "The court of first instance for Pyuthan District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Pyuthan District Headquarters, Nepal",
    phones: ["+977-30-924850"],
    email: "info_pyuthan@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/pyuthan",
    type: "District Court",
    coordinates: [28.11, 82.86],
    parentCourt: "High Court Tulsipur"
  },
  {
    name: "Ramechhap District Court",
    description: "The court of first instance for Ramechhap District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Ramechhap District Headquarters, Nepal",
    phones: ["+977-38-423383"],
    email: "info_ramechhap@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/ramechhap",
    type: "District Court",
    coordinates: [27.32, 86.08],
    parentCourt: "High Court Patan"
  },
  {
    name: "Rasuwa District Court",
    description: "The court of first instance for Rasuwa District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Rasuwa District Headquarters, Nepal",
    phones: ["+977-70-984104"],
    email: "info_rasuwa@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/rasuwa",
    type: "District Court",
    coordinates: [28.11, 85.29],
    parentCourt: "High Court Patan"
  },
  {
    name: "Rautahat District Court",
    description: "The court of first instance for Rautahat District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Rautahat District Headquarters, Nepal",
    phones: ["+977-81-313377"],
    email: "info_rautahat@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/rautahat",
    type: "District Court",
    coordinates: [27.05, 85.32],
    parentCourt: "High Court Janakpur"
  },
  {
    name: "Rolpa District Court",
    description: "The court of first instance for Rolpa District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Rolpa District Headquarters, Nepal",
    phones: ["+977-13-390754"],
    email: "info_rolpa@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/rolpa",
    type: "District Court",
    coordinates: [28.32, 82.63],
    parentCourt: "High Court Tulsipur"
  },
  {
    name: "Rupandehi District Court",
    description: "The court of first instance for Rupandehi District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Rupandehi District Headquarters, Nepal",
    phones: ["+977-32-399691"],
    email: "info_rupandehi@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/rupandehi",
    type: "District Court",
    coordinates: [27.53, 83.39],
    parentCourt: "High Court Tulsipur"
  },
  {
    name: "Salyan District Court",
    description: "The court of first instance for Salyan District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Salyan District Headquarters, Nepal",
    phones: ["+977-38-207979"],
    email: "info_salyan@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/salyan",
    type: "District Court",
    coordinates: [28.37, 82.16],
    parentCourt: "High Court Surkhet"
  },
  {
    name: "Sankhuwasabha District Court",
    description: "The court of first instance for Sankhuwasabha District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Sankhuwasabha District Headquarters, Nepal",
    phones: ["+977-45-924618"],
    email: "info_sankhuwasabha@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/sankhuwasabha",
    type: "District Court",
    coordinates: [27.56, 87.21],
    parentCourt: "High Court Biratnagar"
  },
  {
    name: "Saptari District Court",
    description: "The court of first instance for Saptari District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Saptari District Headquarters, Nepal",
    phones: ["+977-75-287279"],
    email: "info_saptari@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/saptari",
    type: "District Court",
    coordinates: [26.61, 86.74],
    parentCourt: "High Court Janakpur"
  },
  {
    name: "Sarlahi District Court",
    description: "The court of first instance for Sarlahi District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Sarlahi District Headquarters, Nepal",
    phones: ["+977-46-144187"],
    email: "info_sarlahi@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/sarlahi",
    type: "District Court",
    coordinates: [26.95, 85.56],
    parentCourt: "High Court Janakpur"
  },
  {
    name: "Sindhuli District Court",
    description: "The court of first instance for Sindhuli District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Sindhuli District Headquarters, Nepal",
    phones: ["+977-96-537978"],
    email: "info_sindhuli@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/sindhuli",
    type: "District Court",
    coordinates: [27.25, 85.96],
    parentCourt: "High Court Janakpur"
  },
  {
    name: "Sindhupalchok District Court",
    description: "The court of first instance for Sindhupalchok District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Sindhupalchok District Headquarters, Nepal",
    phones: ["+977-11-812334"],
    email: "info_sindhupalchok@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/sindhupalchok",
    type: "District Court",
    coordinates: [27.95, 85.73],
    parentCourt: "High Court Patan"
  },
  {
    name: "Siraha District Court",
    description: "The court of first instance for Siraha District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Siraha District Headquarters, Nepal",
    phones: ["+977-70-168462"],
    email: "info_siraha@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/siraha",
    type: "District Court",
    coordinates: [26.73, 86.23],
    parentCourt: "High Court Janakpur"
  },
  {
    name: "Solukhumbu District Court",
    description: "The court of first instance for Solukhumbu District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Solukhumbu District Headquarters, Nepal",
    phones: ["+977-95-995720"],
    email: "info_solukhumbu@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/solukhumbu",
    type: "District Court",
    coordinates: [27.76, 86.73],
    parentCourt: "High Court Biratnagar"
  },
  {
    name: "Sunsari District Court",
    description: "The court of first instance for Sunsari District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Sunsari District Headquarters, Nepal",
    phones: ["+977-30-491976"],
    email: "info_sunsari@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/sunsari",
    type: "District Court",
    coordinates: [26.61, 87.16],
    parentCourt: "High Court Biratnagar"
  },
  {
    name: "Surkhet District Court",
    description: "The court of first instance for Surkhet District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Surkhet District Headquarters, Nepal",
    phones: ["+977-38-781806"],
    email: "info_surkhet@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/surkhet",
    type: "District Court",
    coordinates: [28.59, 81.63],
    parentCourt: "High Court Surkhet"
  },
  {
    name: "Syangja District Court",
    description: "The court of first instance for Syangja District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Syangja District Headquarters, Nepal",
    phones: ["+977-18-599333"],
    email: "info_syangja@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/syangja",
    type: "District Court",
    coordinates: [28.09, 83.82],
    parentCourt: "High Court Pokhara"
  },
  {
    name: "Tanahun District Court",
    description: "The court of first instance for Tanahun District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Tanahun District Headquarters, Nepal",
    phones: ["+977-11-795030"],
    email: "info_tanahun@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/tanahun",
    type: "District Court",
    coordinates: [27.95, 84.23],
    parentCourt: "High Court Pokhara"
  },
  {
    name: "Taplejung District Court",
    description: "The court of first instance for Taplejung District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Taplejung District Headquarters, Nepal",
    phones: ["+977-19-675065"],
    email: "info_taplejung@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/taplejung",
    type: "District Court",
    coordinates: [27.35, 87.66],
    parentCourt: "High Court Biratnagar"
  },
  {
    name: "Terhathum District Court",
    description: "The court of first instance for Terhathum District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Terhathum District Headquarters, Nepal",
    phones: ["+977-40-923311"],
    email: "info_terhathum@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/terhathum",
    type: "District Court",
    coordinates: [27.14, 87.54],
    parentCourt: "High Court Biratnagar"
  },
  {
    name: "Udayapur District Court",
    description: "The court of first instance for Udayapur District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Udayapur District Headquarters, Nepal",
    phones: ["+977-55-536999"],
    email: "info_udayapur@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/udayapur",
    type: "District Court",
    coordinates: [26.9, 86.52],
    parentCourt: "High Court Biratnagar"
  },
  {
    name: "Western Rukum District Court",
    description: "The court of first instance for Western Rukum District. Has jurisdiction over all major civil and criminal matters occurring within the district.",
    location: "Western Rukum District Headquarters, Nepal",
    phones: ["+977-15-980794"],
    email: "info_westernrukum@supremecourt.gov.np",
    website: "http://supremecourt.gov.np/court/district/westernrukum",
    type: "District Court",
    coordinates: [28.64, 82.47],
    parentCourt: "High Court Surkhet"
  }
];
